### ISSUE TITLE
Write new lexers

### ISSUE THREAD

**Issue by tmbb** [tmbb/makeup#11] opened 2018-03-31 22:24 UTC
Some new lexers I'd like to have (in rough order of priority)

* [x] - Elixir
* [x] - HTML (@tmbb is working on this one)
* [ ] - EEx templates
* [x] - Erlang
* [ ] - Javascript
* [ ] - CSS

**Comment by jamiedumont** [comment] 2018-04-09 07:30
Just found Makeup after searching for a way to recreate Pygments functionality with Elixir. Great repo, cheers!

I won't be able to make a start on it for a while (3-4 weeks?), but I'll happily help out with a few of the lexers.

**Comment by tmbb** [comment] 2018-04-09 14:13
> Great repo, cheers!

Thanks! As you can see, it was heavily modelled on Pygments. In particular, the notions of Lexer, Formatter and Style were basically stolen from Pygments. The styles are also taken from Pygments -- in fact, generated from Pygments classes by the IPython notebook in the repo (no need to reinvent the wheel, especially because I have zero design skills).

> I won't be able to make a start on it for a while (3-4 weeks?)

This isn't ready for someone to start working right now because I want to introduce some changes in preparation for v1.0. Among other changes, I might slightly change the token format so that it is easier to embed lexers inside each other (An eex lexer could be combined by an Elixir lexer + an HTML lexer). and, most importantly, Lexers and Formatters will become behaviours with required callbacks.

> but I'll happily help out with a few of the lexers.

Thanks :) I really need some help with the lexers if this is to become somewhat complete.

I'm working on a mix task to automatically generate a lexer scaffold with sensible defaults which might make it easier to write new lexers.

**Comment by tmbb** [comment] 2018-04-09 15:24
> I'm working on a mix task to automatically generate a lexer scaffold with sensible defaults which might make it easier to write new lexers.

CHANGE OF PLANS: Instead of making a mix task, which is a little cumbersome, I'll just create a [cookiecutter](https://cookiecutter.readthedocs.io/en/latest/) template. Despite cookiecutter's limitations, it's probably the right tool for the job here.

**Comment by jamiedumont** [comment] 2018-04-18 08:30
> This isn't ready for someone to start working right now because I want to introduce some changes in preparation for v1.0.

OK, just give me a shout when I can get stuck in.

**Comment by tmbb** [comment] 2018-05-09 12:16
@jamiedumont I've already introduced the changes I needed. A makeup lexer is now a behaviour with some callbacks you must implement. There is a [cookiecutter template](https://github.com/tmbb/makeup_lexer_cookiecutter)to help you get started. Cookiecutter is a python package that works as a very extensible mix generator (the template repo contains a link to cookiecutter's docs).

I'll start working on an Erlang lexer, so I'd appreciate it if you started on something else.

I think the most useful one would be an HTML lexer (it can help highlighting the docs of packages such as phoenix or Drab, which contain HTML examples) but you're free to implement whatever you prefer.

**Comment by tmbb** [comment] 2018-05-13 23:04
I'm now working on the HTML lexer. People who want to contribute could work on the CSS and Javascript lexers instead.

**Comment by akshatagarwl** [comment] 2020-09-25 03:28
Hey @tmbb I am interested on working in working on some parts of this issue but it's been more than 2 years since the last update. Has any progress been made? Are you still working on this?

**Comment by tmbb** [comment] 2020-09-25 10:12
I han't been working on new lexers for 2 year. But the lexer behaviour is documented in the Makeup docs, so if you want to ontribute a new lexer you can just write a package with a module that implements the `Makeup.Lexer` behaviour and registers itself in the Makeup appliacation.

**Comment by javiergarea** [comment] 2021-05-02 11:17
Hi! I would like to get some feedback about my implementation of an HTML lexer:
https://github.com/javiergarea/makeup_html

Also would like to ask about licensing the makeup_demo project!

Thanks in advance! @tmbb

**Comment by tmbb** [comment] 2021-05-04 12:36
> Hi! I would like to get some feedback about my implementation of an HTML lexer:
https://github.com/javiergarea/makeup_html

It seems great. Now we should somehow integrate it with the Elixir lexer to create an `html.eex` lexer which could be used in the Phoenix docs.

> Also would like to ask about licensing the makeup_demo project!

The old website demo?

**Comment by josevalim** [comment] 2021-05-04 13:52
> The old website demo?

Yes. Shall we transfer it to this org? If so, can you please add a license to it? :)

**Comment by tmbb** [comment] 2021-05-31 22:56
I'm ok with it. I'm not at my PC right now, but I'll add a licence tomorrow. MIT will be fine I think

**Comment by josevalim** [comment] 2021-06-03 19:07
I can also do it, I just need your approval. :)

**Comment by tmbb** [comment] 2021-06-03 22:16
You are super approved! I'm kinda trying to meet a tight deadline, and makeup-related stuff has been suffering.

**Comment by josevalim** [comment] 2021-06-04 05:43
No problem! CAn you give me admin permission in the repo? This way I can add the license and transfer it to the org!

**Comment by josevalim** [comment] 2021-06-08 14:02
With the paper work almost out of the way, @javiergarea, would you like to transfer your repo to the elixir-makeup org? If you make me an admin I can transfer it and give you admin access to the transferred repo.

Sorry for the delay on this.

**Comment by javiergarea** [comment] 2021-06-08 14:39
Sure @josevalim, let's do it!

**Comment by josevalim** [comment] 2021-06-08 18:48
@javiergarea accepted! can you pls make me admin?

**Comment by javiergarea** [comment] 2021-06-08 19:04
There is no option to choose the level of permissions. I can only make you "collaborator" or transfer you the repo (which I tried but it throws an eror since josevalim/makeup_html already exists because of your fork). Would it be possible that I transfer the repo to the organization or that you clean the josevalim/makeup_html name so I transfer the repo to you?

**Comment by josevalim** [comment] 2021-06-08 19:14
@javiergarea i will make you an admin here then, seems easier. :)

**Comment by josevalim** [comment] 2021-06-08 19:15
@javiergarea you should have permission to create repos now on the org, let me know if you can transfer it!

**Comment by javiergarea** [comment] 2021-07-13 18:58
@tmbb any update on licensing `makeup_demo`? I would like to update it and include HTML in the supported langs :)

**Comment by Billzabob** [comment] 2021-08-31 15:10
[I made a lexer for GraphQL](https://github.com/Billzabob/makeup_graphql). The problem is that it doesn't seem to be working when I test it and I'm not sure what I'm doing wrong:
<img width="321" alt="Screen Shot 2021-08-31 at 8 57 09 AM" src="https://user-images.githubusercontent.com/3711832/131527753-ded13507-51a1-47d2-9d42-71b07f84ffc5.png">

Looks like this when the docs are generated with no syntax highlighting:
<img width="850" alt="Screen Shot 2021-08-31 at 8 56 55 AM" src="https://user-images.githubusercontent.com/3711832/131527775-81456283-15eb-46ea-a207-1834aca3f6a0.png">

Here's some iex output from another project that I'm trying to test it with where it seems to be working properly:
```elixir
Interactive Elixir (1.12.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> lexer = Makeup.Registry.get_lexer_by_name("graphql")
{MakeupGraphql, []}
iex(2)> Makeup.Registry.supported_language_names()
["graphql"]
iex(3)> graphql = """     
...(3)> mutation {
...(3)>   foo(input: {
...(3)>     test: ["This is a GraphQL mutation"],
...(3)>     reason: LOST,
...(3)>     foo: 10,
...(3)>     bar: 1.0
...(3)>   }) {
...(3)>     success
...(3)>   }
...(3)> }
...(3)> """
"mutation {\n  foo(input: {\n    test: [\"This is a GraphQL mutation\"],\n    reason: LOST,\n    foo: 10,\n    bar: 1.0\n  }) {\n    success\n  }\n}\n"
iex(4)> MakeupGraphql.lex(graphql)
[
  {:keyword_reserved, %{language: :graphql}, 'mutation'}, 
  {:whitespace, %{language: :graphql}, " "},
  {:punctuation, %{language: :graphql}, 123},
  {:whitespace, %{language: :graphql}, 10},
  {:whitespace, %{language: :graphql}, "  "},
  {:name, %{language: :graphql}, 'foo'},
  {:punctuation, %{language: :graphql}, 40},
  {:keyword_reserved, %{language: :graphql}, 'input'},
  {:punctuation, %{language: :graphql}, 58},
  {:whitespace, %{language: :graphql}, " "},
  {:punctuation, %{language: :graphql}, 123},
  {:whitespace, %{language: :graphql}, 10},
  {:whitespace, %{language: :graphql}, "    "},
  {:name, %{language: :graphql}, 'test'},
  {:punctuation, %{language: :graphql}, 58},
  {:whitespace, %{language: :graphql}, " "},
  {:punctuation, %{language: :graphql}, 91},
  {:string, %{language: :graphql},
   ["\"", 84, 104, 105, 115, 32, 105, 115, 32, 97, 32, 71, 114, 97, 112, 104,
    81, 76, 32, 109, 117, 116, 97, 116, 105, 111, 110, "\""]},
  {:punctuation, %{language: :graphql}, 93},
  {:punctuation, %{language: :graphql}, 44},
  {:whitespace, %{language: :graphql}, 10},
  {:whitespace, %{language: :graphql}, "    "},
  {:name, %{language: :graphql}, 'reason'},
  {:punctuation, %{language: :graphql}, 58},
  {:whitespace, %{language: :graphql}, " "},
  {:name, %{language: :graphql}, 'LOST'},
  {:punctuation, %{language: :graphql}, 44},
  {:whitespace, %{language: :graphql}, 10},
  {:whitespace, %{language: :graphql}, "    "},
  {:name, %{language: :graphql}, 'foo'},
  {:punctuation, %{language: :graphql}, 58},
  {:whitespace, %{language: :graphql}, " "},
  {:number_integer, %{language: :graphql}, '10'},
  {:punctuation, %{language: :graphql}, 44},
  {:whitespace, %{language: :graphql}, 10},
  {:whitespace, %{language: :graphql}, "    "},
  {:name, %{language: :graphql}, 'bar'},
  {:punctuation, %{language: :graphql}, 58},
  {:whitespace, %{language: :graphql}, " "},
  {:number_float, %{language: :graphql}, '1.0'},
  {:whitespace, %{language: :graphql}, 10},
  {:whitespace, %{language: :graphql}, "  "},
  {:punctuation, %{language: :graphql}, 125},
  {:punctuation, %{language: :graphql}, 41},
  {:whitespace, %{language: :graphql}, " "},
  {:punctuation, %{language: :graphql}, 123},
  {:whitespace, %{language: :graphql}, 10},
  {:whitespace, %{...}, ...},
  {:name, ...},
  {...},
  ...
]
```

**Comment by josevalim** [comment] 2021-09-01 15:24
@Billzabob fixed here: https://github.com/elixir-lang/ex_doc/commit/b25a0008f505258e42257d3c59af5ea7daaa5fae

**Closed as completed** 2022-02-13 19:21 UTC
Labels: help wanted
